channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - astropy
  - bumpversion
  - colorama
  - cython
  - folium
  - h5py
  - ipython
  - line_profiler
  - markdown
  - matplotlib
  - mypy
  - netCDF4
  - numpy
  - pandas
  - pelican
  - pycurl
  - pytest
  - pytest-cov
  - python-editor
  - requests
  - scipy
  - seaborn
  - cartopy
